# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
      ------------------APDS POE Configure(basc ones based on the CircleCi yml that it created. 
      version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Example Docker image (you can change this to suit your project)
    steps:
      - checkout  # Check out the code from the Git repository
      - run:
          name: Install dependencies
          command: |
            python -m venv venv  # Create virtual environment
            . venv/bin/activate   # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies from requirements.txt
      - run:
          name: Run tests
          command: |
            pytest  # Run tests using pytest (adjust based on your project)

workflows:
  version: 2
  build:
    jobs:
      - build
